### ISSUE TITLE
Start Viewer instead of "[SyncTex:] viewer is not running"

### ISSUE THREAD

**Issue by petRUShka** [coot/atp_vim#35]
It is quite smart behavior for editor to call viewer in case user asked for the viewer (with forward search) and there is no viewer running. Now it is just echoed 
  
    [SyncTex:] viewer is not running"

in that case.

My proposal:
If i press `F3` (for example) in order to perform forward search ATP should run viewer if there is no viewer running.

See `atp_vim/autoload/atplib/compiler.vim:108`

**Comment by heiderich** [comment]
I also experienced this. The problem seems to be that some names did change in a recent of psutil. I addressed this in pull request #36. Does this solve the problem for you too?

**Comment by petRUShka** [comment]
I cannot answer this question because I switched to `vimtex` plugin.

**Comment by coot** [comment]
@heiderich I am closing, but re-open if you have an issue with it.
